### ISSUE TITLE
Significant lag on PRs merged

### ISSUE THREAD

**Issue by MattIPv4** [remotion-dev/github-unwrapped#179]
👋 Wonderful to see this once again! I'm noticing that the animation chugs hard on the PRs merged section for my profile. I'm on an M1 MacBook Pro, viewing the site in Firefox Developer Edition. Let me know if any other details would be useful!

**Comment by JonnyBurger** [comment]
Acknowledge this issue! 

This is a SVG with a huge viewBox, somehow this is expensive for browsers to display when zoomed in.
For Webkit/Chrome, it is for some reason less expensive.

We actually already optimized it as far as we can by not rendering the bottom part of the SVG when doing the zoom in animation at the end. Therefore we don't plan any further optimizations also because the endgoal is to generate an MP4 which does play smoothly.
